### PR TITLE
Add Module from Focus or Category

### PR DESCRIPTION
**Pull request by StefanieJaeger**

### CODE REVIEW

**Comment by captainwuushuu** [comment]
Maybe add some padding/margin between the listed items in the Vertiefungen, so the buttons don't sit on top of each other. Other than that KUDOS THIS IS FUCKING NICEEEEE

**Comment by StefanieJaeger** [comment]
Improved the styling:
image
image
Decided to make the background of the dropdown pink, to have it not disappear into the Semester component. This is temporary tho, until we update the ModuleSearch component.

**Comment by StefanieJaeger** [comment]
I will try a slight optimization of the data. Something like an internal state, to not duplicate modules as much.

**Comment by StefanieJaeger** [comment]
Also, Jeremy had a good idea. If we realize that adding modules does not work well on Mobile, then we could always hide those buttons. Since we had noone who used Mobile for editing.

**Pull request merged**
